name: deploy-production
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  workflow_dispatch:
  push:
    branches:
      - main
concurrency:
  group: deploy-production-workflows
  cancel-in-progress: false
jobs:
  deploy-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            src
            public
      - uses: actions/cache/restore@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-cache
      - run: npm install --global --prefer-offline vercel@latest
      - run: vercel --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
  run-migrations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            migrations
      - uses: actions/cache/restore@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-cache
      - run: npm install --global --prefer-offline vercel@latest
      - run: vercel env pull --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - uses: actions/cache/restore@v4
        with:
          path: /opt/pipx_bin/direnv
          key: ${{ runner.os }}-direnv
          fail-on-cache-miss: true
      - run: |
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          direnv allow .
          direnv export gha > "$GITHUB_ENV"
      - uses: actions/cache/restore@v4
        with:
          path: /usr/local/bin/atlas
          key: ${{ runner.os }}-atlas
          fail-on-cache-miss: true
      - run: atlas migrate apply --url $DATABASE_URL --revisions-schema "public" --dir "file://migrations"
